### ISSUE TITLE
[DevOps] Plan horizontal scaling / swarming of UCI backend

### ISSUE THREAD

**Issue by karntrehan** [samagra-comms/docker-deploy#26]
- [ ] Fix Docker compose of docker deploy before hand
- [ ] Docker swarm cluster to be provisioned and setup
    - [ ] Master node 
    - [ ] Slave node (we can increase the spec later as load increases)
- [ ] Another node needed for stateful DBs 
- [ ] Transfer all data from current deployment to new deployment
- [ ] Testing e2e before making the swarm cluster prod

**Comment by tushar5526** [comment]
```
Swarm deployment of UCI is ready for testing.
Server Configuration:

UCI-Docker-Swarm-Master : 142.93.217.128 - Holds all the stateless services
Specs: 8GB RAM Basic CPU BLR datacenter 

UCI-DB : 139.59.42.92 - Holds all the stateful services - Redis, Postgres, Cassandra, Kafka cluster
Specs: 8GB RAM Basic CPU BLR datacenter 

We can scale horizontally by adding new slave to docker cluster and DBs data are mounted as directories for easier backups and scaling of disk size. We can add a volume and move the DB data to there when needed. All DBs connect to services using Digital Ocean's VPC - private IP
```

**Comment by karntrehan** [comment]
ODK aggregate password not taken from env. Need to fix in #23.

Org and OwnerID to be created. AdapterIDs to be created.

**Comment by karntrehan** [comment]
Nirali to start testing end to end from Admin panel to UCI FE. Updated build to be shared by @karntrehan

**Comment by Nirali010129** [comment]
Hey, @karntrehan this is done, bug report was shared with you, on Discord.
