### ISSUE TITLE
Remove exposure of 9080 port in inbound

### ISSUE THREAD

**Issue by karntrehan** [samagra-comms/docker-deploy#27]
Security concern is to remove the exposure of 9080 port.

**Comment by tushar5526** [comment]
@pankajjangid05 is there any security concern in the inbound service ? Can you set more context in this, if you know something.

**Comment by geeky-abhishek** [comment]
@pankajjangid05  & @chinmoy12c to schedule a call to discuss this.

**Comment by chinmoy12c** [comment]
@tushar5526 any updates here?

**Comment by chinmoy12c** [comment]
@chinmoy12c and @pankajjangid05 to work on this on staging for testing.

**Comment by susheelvar** [comment]
@pankajjangid05 to push to staging today.

**Comment by pankajjangid05** [comment]
**Exposures are removed for these services:**

- [ ] Inbound
- [ ] Outbound
- [ ] Orchestrator
- [ ] Transformer
- [ ] Broadcast-Transformer


**Problems facing:** 

- When the web channel accesses the conversation history API from the outer side.
- When trying to load testing from the outer side.
- Netcore/Gupshup calling our inbound API from another server.

**Comment by susheelvar** [comment]
Port temporarily opened on staging, to be closed after load testing completed.

**Comment by susheelvar** [comment]
@chinmoy12c @pankajjangid05 to create backlog ticket (to be picked up for later).

**Comment by chinmoy12c** [comment]
Here is the sheet which contains all the endpoints of the transaction layer and where they are used:
https://docs.google.com/spreadsheets/d/12Pc1YxLxNeuGcbZX-fTeLYSvPbq_rbhpVNxYAfHB5WA/edit#gid=0

**Comment by chinmoy12c** [comment]
This is tracked by sub issues:

https://github.com/samagra-comms/uci-apis/issues/74
https://github.com/samagra-comms/uci-apis/issues/75
https://github.com/samagra-comms/uci-apis/issues/76
