### ISSUE TITLE
Load testing

### ISSUE THREAD

**Issue by karntrehan** [samagra-comms/docker-deploy#28]
Flow

- [ ] Create a form
- [ ]  Upload a form
- [ ]  Send Broadcast

API

- [ ] Create a dummy API that generates 10k users

**Comment by karntrehan** [comment]
@ChakshuGautam please share an update as to when this will be started.

**Comment by karntrehan** [comment]
@karntrehan to work on adding more elements for load testing = Number of users, scenarios, expected numbers, etc.

**Comment by karntrehan** [comment]
Priority changes to P0.

**Comment by karntrehan** [comment]
Load test on UCI on bot creation and broadcast: 

| **API**                  | **Peak load** | **Target p90** | **Target p95** | **Target p99** |
|--------------------------|---------------|----------------|----------------|----------------|
| /admin/form/upload       | 1000          | 100ms          | 115ms          | 130ms          |
| /admin/conversationLogic | 2000          | 100ms          | 115ms          | 130ms          |
| /admin/bot               | 1000          | 100ms          | 115ms          | 130ms          |
| /admin/user-segment      | 1000          | 100ms          | 115ms          | 130ms          |
| /admin/bot/start         | 1000000       | 120ms          | 140ms          | 150ms          |

This is for a bot targeting 2L users. 

Suggested framework for running tests - https://k6.io/docs/
Server to run tests on - 142.93.217.128 + 139.59.42.92 (Pre-Pod)

**Comment by ChakshuGautam** [comment]
Sharing some notes here.

1. `/admin/form/upload` What does `Peak Load` signify here? Are we going to upload 1000 forms to ODK or will try to get to 1000 uploads/second as peak load? Should this API be load tested? I think same applies for all other APIs well.
2. `/admin/conversationLogic` - Is this GET or POST? GET will be used a log POST not so much so I guess this is POST.
3. `/admin/bot` - Same as the other one.
4. `/admin/bot/start` - Gets triggered one time for a batch of users (say 500) then gets triggered say a second after for 500 more until pagination ends.

**Comment by karntrehan** [comment]
`/admin/form/upload`
>  ... 1000 uploads/second as peak load?
Yes. 1000 uploads / second is what I was thinking. 
> Should this API be load tested? 
I think it should be integration tested for sure, not sure about load. Same applies to others as well. We should instead test `/admin/bot/allContextual`, `campaign/start?campaignId` & the conversation web socket itself. WDYT? 

`/admin/conversationLogic`
> so I guess this is POST
Yes. As above, I don't think this should be load tested as well.

`/admin/bot`
As above, I don't think this should be load tested as well.

`/admin/bot/start`
> until pagination ends. 
Is this already implemented as part of https://github.com/samagra-comms/broadcast-transformer/issues/2? If yes, then we should focus on https://github.com/samagra-comms/broadcast-transformer/issues/1 and then plan load testing for 2L user together and see the latency we produce with a size of 500.

**Comment by karntrehan** [comment]
Load test for UCI on bot broadcast & conversation: 

| **API**                    | **Peak load / sec** | **Target p90** | **Target p95** | **Target p99** |
|----------------------------|---------------------|----------------|----------------|----------------|
| /admin/bot/start           | 10,00,000           | 120ms          | 140ms          | 150ms          |
| /admin/bot/allContextual   | 2,00,000            | 100ms          | 110ms          | 120ms          |
| /campaign/start?campaignId | 10,00,000           | 120ms          | 140ms          | 150ms          |
| /xmsg/conversation-history | 2,00,000            | 100ms          | 110ms          | 120ms          |
| ws:connect                 | 2,00,000            | 20ms           | 30ms           | 40ms           |
| ws:botRequest              | 2,00,000            | 30ms           | 40ms           | 50ms           |
| ws:botResponse             | 2,00,000            | 50ms           | 75ms           | 100ms          |

Suggested framework for running tests - https://k6.io/docs/ & https://k6.io/docs/using-k6/protocols/websockets/
Server to run tests on - 142.93.217.128 + 139.59.42.92 (Pre-Pod)

Please review - @ChakshuGautam & @suresh12

**Comment by ChakshuGautam** [comment]
It seems like the current peak load is a couple of magnitudes higher than what UCI can support right now. To give an example 2x10^5 messages per second would be 1.5 Billion messages getting sent to users in a Day which is not something that UCI can do right now.

**Comment by karntrehan** [comment]
Will continue on this from Tuesday.

**Comment by karntrehan** [comment]
To be picked up on Monday.

**Comment by karntrehan** [comment]
@karntrehan to schedule call with @choxx on Tuesday.

**Comment by karntrehan** [comment]
We shall be stress testing the below APIs and identifying performance + breakage points. 

| **API**                    |
|----------------------------|
| /admin/bot/start           |
| /admin/bot/allContextual   |
| /campaign/start?campaignId |
| /xmsg/conversation-history |
| ws:connect                 |
| ws:botRequest             |
| ws:botResponse            |

Yuvraj to execute with help from @choxx on K6 and @chinmoy12c on UCI context.

**Comment by chinmoy12c** [comment]
@chinmoy12c to share sample curl requests of these APIs.

**Comment by chinmoy12c** [comment]
Hey @yuvrajsab this is the curl for the endpoints:

`/admin/bot/allContextual`

```
curl --location 'http://localhost:3002/admin/bot/allContextual' \
--header 'Accept: application/json, text/plain, /' \
--header 'Accept-Language: en-US,en;q=0.9' \
--header 'Connection: keep-alive' \
--header 'Content-Type: application/json' \
--header 'Origin: http://localhost:3009/' \
--header 'Referer: http://localhost:3009/' \
--header 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36' \
--header 'admin-token: [ADMIN_TOKEN]' \
--header 'asset: conversationLogic' \
--header 'ownerID: 8f7ee860-0163-4229-9d2a-01cef53145ba' \
--header 'ownerOrgID: org01' \
--header 'Cookie: fusionauth.locale=en_US; fusionauth.sso=AgOat0GjncGOHhPpH_HuL9QQqnfMitd15O-ofS-uTcdA'
```

**Comment by pankajjangid05** [comment]
Hey @yuvrajsab this is the curl for the endpoints:

/xmsg/conversation-history


curl --location --request GET 'http://localhost:8085/xmsg/conversation-history?provider=pwa&endDate=27-04-2023&startDate=21-03-2023&botId=BOTID&userId=ucipwa:mobilenumber'

**Comment by chinmoy12c** [comment]
@pankajjangid05  and @chinmoy12c to setup the test user. @karntrehan to provide FCM token for the test user.

**Comment by susheelvar** [comment]
@karntrehan provided FCM. @pankajjangid05 & @chinmoy12c to connect to resolve.

**Comment by pankajjangid05** [comment]
User Segment is created on staging @yuvrajsab Now you can start testing /campaign/start?campaignId API

**Comment by pankajjangid05** [comment]
Hey @yuvrajsab 

Curl for ` /campaign/start?campaignId`

curl --location --request GET 'http://localhost:8085/campaign/start?campaignId=FCM-BOT-ID'

**Comment by susheelvar** [comment]
@pankajjangid05 to share server access with @yuvrajsab.

**Comment by susheelvar** [comment]
- [ ] Deploy web channel to staging - by @pankajjangid05 and @geeky-abhishek

**Comment by yuvrajsab** [comment]
My load testing learning documented here in this doc: https://docs.google.com/document/d/1xfIGxxxus01xxGR4uh048tqkp4Q3IXkg9byfpEpcPog/edit?usp=sharing

**Comment by karntrehan** [comment]
Load testing methodology looks fine. We should run the tests now on prod for final numbers.

**Comment by susheelvar** [comment]
@yuvrajsab to run load testing on pre-prod today; to be discussed with Chakshu, Suresh, Karan tomorrow.

**Comment by karntrehan** [comment]
Test ran on Prod (Services) & Pre Prod (DB):
* All contextual - ~1,40,000 requests in 10 mins.
* History - ~60,000 requests in 10 mins

**Comment by yuvrajsab** [comment]
* System config
   Server 1: where services are deployed.
CPU: Intel(R) Xeon(R) CPU E5-2697A v4 @ 2.60GHz
CPU Arch: x86_64
CPU count: 16
Memory: 16GiB DIMM RAM
Disk: 155G HDD

   Server 2: where db and redis are deployed.
CPU: DO-Premium-Intel 2.0GHz
CPU Arch: x86_64
CPU count: 8
Memory: 16GiB DIMM RAM
Disk: 155G HDD

* Tests
  * Contextual
    * Called when: we want the list of all the bots.
    * Load Test
      * No. of Requests = 200000
      * Success = 60033
      * Failure = 139967
      * P99 = 6838ms
      * P95 = 5065.6ms
      * P90
      * System load = stable (services: 1.6 & db: 0.15)
  * History
    * Called when: we want the previous conversation with the bot.
    * Load Test
        * No. of Requests = 200000
        * Success = 26203
        * Failure = 173821
        * P99 = 8868.4ms
        * P95 = 6187.2ms
        * P90
        * System load = stable (services: 1.6 & db: 0.65)
* Next steps

**Comment by chinmoy12c** [comment]
@karntrehan to review the results here.

**Comment by geeky-abhishek** [comment]
Optimise the server first then will test it @yuvrajsab

**Comment by susheelvar** [comment]
Load testing results:
- allContextual only able to support 96 requests in place of 2L configured
- historyAPI timing out

**Comment by karntrehan** [comment]
To be picked up post cache addition to UCI APIs by @RyanWalker277

**Comment by susheelvar** [comment]
To be picked after other backend changes are closed and deployed.

**Comment by karntrehan** [comment]
Load testing to start from today.

**Comment by susheelvar** [comment]
Load testing to be picked up once prod is running. Till then, load testing is parked. 
Changes on staging to be merged to prod after testing.

**Comment by aakashyadav-kgp** [comment]
@yuvrajsab and @chinmoy12c to close this today

**Comment by karntrehan** [comment]
Prod not ready. Deployment done yesterday leading to errors in typescript. 
@geeky-abhishek and @chinmoy12c to connect on this.

**Comment by yuvrajsab** [comment]
Load test conducted on 27-6-2023.

| API | Requests | Success | Failed | Timeout Requests | Timeout Seconds | P90 | P95 | P99 |
| --- | -------- | ------- | ------ | ---------------- | --------------- | --- | --- | --- |
| /admin/bot/allContextual | 200000 | 71740 | - | 128260 | 15s | 432.7 | 528.6 | 907 |
| /xmsg/conversation-history | 200000 | 40777 | - | 159223 | 15s | 4965.3 | 5598.4 | 7557.1 |
| /admin/bot/allContextual | 200000 | 101295 | - | 98705 | 25s | 645.6 | 854.2 | 2186.8 |
| /xmsg/conversation-history | 200000 | 37632 | - | 161290 | 25s | 17859.2 | 21381.5 | 24107.7 |

**Comment by aakashyadav-kgp** [comment]
UCI Transport socket service is not working on production.

**Comment by karntrehan** [comment]
Caching PRs to be merged and deployed to staging + prod.

**Comment by yuvrajsab** [comment]
Load tested on 05-07-2023.

| API | Requests | Success | Failed | Timedout Requests | Timeout Seconds | P90 | P95 | P99 |
| --- | -------- | ------- | ------ | ---------------- | --------------- | --- | --- | --- |
| /admin/bot/allContextual | 200000 | 72189 | - | 127915 | 15s | 632.8 | 944 | 2515.5 |
| /xmsg/conversation-history | 200000 | 85135 | - | 114865 | 15s | 89.1 | 117.9 | 295.9 |
| /admin/bot/allContextual | 200000 | 81323 | - | 118677 | 25s | 620.3 | 820.7 | 1525.7 |
| /xmsg/conversation-history | 200000 | 43749 | 6 | 156245 | 25s | 104.6 | 144 | 383.8 |

**Comment by karntrehan** [comment]
To pick up socket testing as system is now performant.

**Comment by geeky-abhishek** [comment]
@yuvrajsab  will pick this today

**Comment by karntrehan** [comment]
@chinmoy12c @yuvrajsab and @geeky-abhishek to test this together to figure issue with Async which came out in yesterdays trigger. 


![Image](https://github.com/samagra-comms/docker-deploy/assets/5885669/e1615be3-8ebf-4ef3-839a-1943ffc3400c)

**Comment by karntrehan** [comment]
@yuvrajsab to discuss with @ChakshuGautam about the AKAI testing suite and try to replicate the same here.

**Comment by geeky-abhishek** [comment]
@yuvrajsab to connect with amruth today

**Comment by karntrehan** [comment]
Script created with custom clients. Script ran on staging. @yuvrajsab to share performance.

**Comment by yuvrajsab** [comment]
While testing on 02/08/2023, We noticed that
when the load was 100000 client tried to connect at intervals of 100ms, we got.

![Image](https://github.com/samagra-comms/docker-deploy/assets/27115069/e3784632-54d9-4e2f-8f8a-8d40dbe3ec46)

when we tried to load test 100000 clients at intervals of 10ms, we got.

![Image](https://github.com/samagra-comms/docker-deploy/assets/27115069/19b02f4d-47aa-4ebf-a721-dcbf70af0196)

when we tried to load test with 15000 clients trying to connect at intervals of 10ms, we got.

![Image](https://github.com/samagra-comms/docker-deploy/assets/27115069/e6779c2c-69c5-4ecc-b3d5-03a4071e67ff)

when we tried to load test with 8000 clients trying to connect at intervals of 10ms, we got.

**Comment by ChakshuGautam** [comment]
[Transformer Scaling](https://docs.google.com/spreadsheets/d/1q4Wa6ZHOvK_tsw3tAnT2DkKEsVDe3VUICIiitMpnavo/edit?usp=sharing)

**Comment by karntrehan** [comment]
Prod load test on Sockets as well as APIs to be undertaken today at 5 pm.

**Comment by karntrehan** [comment]
Script needs to be updated. Every connection to be made from a unique user. Dump of users to be provided by @chinmoy12c

**Comment by aakashyadav-kgp** [comment]
@yuvrajsab add the data you need here for @karntrehan

**Comment by yuvrajsab** [comment]
need `phone number` and `token` to test. cc @karntrehan

**Comment by karntrehan** [comment]
On load testing, we identified that 900 unique users are supported for socket connection. Socket connection logs were not found on transport layer. @chinmoy12c to debug on this.

**Comment by geeky-abhishek** [comment]
@yuvrajsab to update the table and share the script with @chinmoy12c

**Comment by yuvrajsab** [comment]
#### Socket loadtest result:

##### Scenario:

We have 8000 unique users trying to connect with the socket and after the connection establishes they wait for 1 second and then do `/botRequest` then on response receive we are again doing the `/botRequest` so that socket doesn't set in the ideal state. So each user will do at most 10 requests in total.


| API | Requests | Success | Failed | Unique user | Disconnected | P90 (ms) | P95 (ms) | P99 (ms) |
| --- | -------- | ------- | ------ | ----------- | ------------ | -------- | -------- | -------- |
| /botRequest | 10186 | 2285 | 0 | 1171 | 0 | 8231.6 | 9264.8 | 10280.32 |
