### ISSUE TITLE
Fix installv2.sh & create secrets at install time

### ISSUE THREAD

**Issue by karntrehan** [samagra-comms/docker-deploy#29]
Installv2 is currently broken. We need to fix it to allow users to install the UCI system seamlessly.

**Comment by karntrehan** [comment]
@tushar5526 to cordinate with @pankajjangid05 and @chinmoy12c to work on this.

**Comment by rohithinnomick** [comment]
Team, may i know any update about this issue ??

**Comment by karntrehan** [comment]
@rohithinnomick we are tracking #23 and is in progress.

**Comment by rohithinnomick** [comment]
Ok team Thanks for the update

**Comment by karntrehan** [comment]
@rohithinnomick We almost done with the fixes. We shall have the fixed version for you by tomorrow EOD. cc @tushar5526

**Comment by rohithinnomick** [comment]
Thanks Team

**Comment by tushar5526** [comment]
Hey @rohithinnomick https://github.com/samagra-comms/docker-deploy#manual-setup---one-click-deployment-is-wip please use this guide to get started.

**Comment by karntrehan** [comment]
Hie @rohithinnomick were you able to test this out?

**Comment by rohithinnomick** [comment]
I am trying to install dependencies using docker-deploy.
After run the command bash installv2.sh after some time it is auto exist from the terminal. And getting this error.
![image](https://user-images.githubusercontent.com/80948519/234775339-68f54635-43ab-4fa9-92d8-d1102e641c4d.png)

**Comment by tushar5526** [comment]
Is there enough memory ? You can cap elastic search to consume less memory or comment out elastic search and then do docker compose up.

**Comment by rohithinnomick** [comment]
There is no memory issue. And If i comment elastic search and do docker compose up. It is giving error.
![image](https://user-images.githubusercontent.com/80948519/235065544-0ecd6401-4f41-43d4-84bb-50a336bf32a4.png)
