### ISSUE TITLE
Dev and Staging Setup Improvement

### ISSUE THREAD

**Issue by ChakshuGautam** [samagra-comms/docker-deploy#30]
- [ ] 1. Auto push to dev and staging
- [ ] 2. Remote SSH to develop during dev using Intellij; Once it breaks, start services manually using compose.
- [ ] 3. We currently have 3 systems. 1 swarm, 1 mono prod and 1 staging. We will cleanup that as well.

**Comment by karntrehan** [comment]
@ChakshuGautam can you explain the 2nd point to @tushar5526 ?

**Comment by karntrehan** [comment]
We currently have 3 systems. 1 swarm, 1 mono prod and 1 staging. We will cleanup that as well.

**Comment by karntrehan** [comment]
Staging / Prod decision

Currently we have setup UCI on 3 combinations: 
1. 143.110.255.220 + 143.110.183.73 - V2 staging
2. 142.93.217.128 + 139.59.42.92 - WIP Swarm deployment
3. 159.65.151.114 - Current NL Prod

Decision: 
1. 143.110.255.220 + 143.110.183.73 = Shutdown / Deprecate
2. 142.93.217.128 + 139.59.42.92 = Complete and use as Prod for NL
3. 159.65.151.114 = Once 2 is complete, make this staging for UCI

**Comment by tushar5526** [comment]
143.110.255.220 + 143.110.183.73 = Shutdown / Deprecate
One of these servers is Chakshu's dev env which will not be shutdown. Other server can be shutdown if it is only being used for UCI dev and we no longer need v1 APIs. 

A good strategy will be to turn off the server for few days first to identify if any other program/service is using this.

**Comment by tushar5526** [comment]
@pankajjangid05 needs to add requirements. If possible you can take a dump of DBs yourself as well.

**Comment by pankajjangid05** [comment]
@tushar5526 sure I will take it.

**Comment by susheelvar** [comment]
Completed - @tushar5526 to post update on Discord.

**Comment by tushar5526** [comment]
Posted on Discord.
