### ISSUE TITLE
Unable to create conversation logic in admin UI

### ISSUE THREAD

**Issue by rohithinnomick** [samagra-comms/docker-deploy#31]
I cloned the repo https://github.com/samagra-comms/docker-deploy
and then run the command bash installv2.sh in source directory
and I tried to create a conversation logic in admin UI. I am able to upload xml file. But create api is not working.

I am using Ubuntu os

**Comment by karntrehan** [comment]
Linked to #29

**Comment by tushar5526** [comment]
Will be covered in https://github.com/samagra-comms/docker-deploy/issues/23
