### ISSUE TITLE
.env refactoring and clean up 

### ISSUE THREAD

**Issue by tushar5526** [samagra-comms/docker-deploy#33]
```
  uci-transport-socket:
    image: samagragovernance/uci-transport-socket:655da87
    container_name: uci-transport-socket
    .
    ..
    ...
    env_file: env.prod/ts.env #Secrets unique to each service and not shared among other environments:
    environment:
      ADMIN_TOKEN: ${FUSION_AUTH_ADMIN} #Secrets that are the same and shared between multiple services 
   ```
   
cc @karntrehan @ChakshuGautam

**Comment by chinmoy12c** [comment]
<details>
<summary>Here is the filtered list of env variables for transformer. </summary>
<br>

```
ASSESSMENT_GO_TO_START_CHAR
AZURE_BLOB_STORE_ACCOUNT_KEY
AZURE_BLOB_STORE_ACCOUNT_NAME
AZURE_BLOB_STORE_CONTAINER
BOOTSTRAP_SERVERS
CAFFEINE_CACHE_EXPIRE_DURATION
CAFFEINE_CACHE_MAX_SIZE
CAMPAIGN_ADMIN_TOKEN
CAMPAIGN_URL
CASSANDRA_KEYSPACE
CASSANDRA_PORT
CASSANDRA_URL
CDN_MINIO_APP_ID
CDN_MINIO_BUCKET_ID
CDN_MINIO_FA_KEY
CDN_MINIO_FA_URL
CDN_MINIO_LOGIN_ID
CDN_MINIO_PASS
CDN_MINIO_URL
DOUBTNUT_AUTH_KEY
DOUBTNUT_BASE_URL
DOUBTNUT_WELCOME_MSG
DOUBTNUT_WELCOME_VIDEO
ENV
EXHAUST_TELEMETRY_ENABLED
FORMS_DB_HOST
FORMS_DB_NAME
FORMS_DB_PASSWORD
FORMS_DB_PORT
FORMS_DB_URL
FORMS_DB_USERNAME
FUSIONAUTH_KEY
FUSIONAUTH_URL
KAFKA_CAMPAIGN_TOPIC
KAFKA_GENERIC_TRANSFORMER_TOPIC
KAFKA_LOGS_TOPIC
KAFKA_ODK_TRANSFORMER_TOPIC_PATTERN
KAFKA_OUTBOUND_TOPIC
KAFKA_PROCESS_OUTBOUND
KAFKA_TELEMETRY_TOPIC
NLAPP_USER_AUTH
NLAPP_USER_URL
NLAPP_USER_XAPPID
ODK_PASS
ODK_URL
ODK_USER
POSTHOG_EVENT_ENABLED
REDIS_DB_INDEX
REDIS_HOST
REDIS_NUMBER_PORT
REGISTRY_URL
SUNBIRD_CLOUD_MEDIA_STORAGE_CONTAINER
SUNBIRD_CLOUD_MEDIA_STORAGE_KEY
SUNBIRD_CLOUD_MEDIA_STORAGE_SECRET
SUNBIRD_CLOUD_MEDIA_STORAGE_TYPE
SUNBIRD_CLOUD_MEDIA_STORAGE_URL
TELEMETRY_EVENT_PDATA_ID
```

</details>

Also noticed some problems with the current env file:

**Missing Keys:**

SUNBIRD_CLOUD_MEDIA_STORAGE_CONTAINER		
SUNBIRD_CLOUD_MEDIA_STORAGE_KEY		
SUNBIRD_CLOUD_MEDIA_STORAGE_SECRET		
SUNBIRD_CLOUD_MEDIA_STORAGE_TYPE		
SUNBIRD_CLOUD_MEDIA_STORAGE_URL
KAFKA_GENERIC_TRANSFORMER_TOPIC

**Misnamed:**
CDN_MINI_LOGIN_ID -> CDN_MINIO_LOGIN_ID
REDIS_PORT -> REDIS_NUMBER_PORT

**Comment by chinmoy12c** [comment]
<details>
<summary>Here is the filtered list of env variables for orchestrator. </summary>
<br>

```
AZURE_BLOB_STORE_ACCOUNT_KEY
AZURE_BLOB_STORE_ACCOUNT_NAME
AZURE_BLOB_STORE_CONTAINER
BOOTSTRAP_SERVERS
CAFFEINE_CACHE_EXPIRE_DURATION
CAFFEINE_CACHE_MAX_SIZE
CAMPAIGN_URL
CASSANDRA_KEYSPACE
CASSANDRA_MIGRATION_COUNT
CASSANDRA_PORT
CASSANDRA_URL
CDN_MINIO_APP_ID
CDN_MINIO_BUCKET_ID
CDN_MINIO_FA_KEY
CDN_MINIO_FA_URL
CDN_MINIO_LOGIN_ID
CDN_MINIO_PASS
CDN_MINIO_URL
ENV
FORMS_DB_HOST
FORMS_DB_NAME
FORMS_DB_PASSWORD
FORMS_DB_PORT
FORMS_DB_USERNAME
FUSIONAUTH_KEY
FUSIONAUTH_URL
KAFKA_BROADCAST_TRANSFORMER_TOPIC
KAFKA_CAMPAIGN_TOPIC
KAFKA_GENERIC_TRANSFORMER_TOPIC
KAFKA_INBOUND_PROCESSED_TOPIC
KAFKA_ODK_TRANSFORMER_TOPIC
KAFKA_OUTBOUND_TOPIC
KAFKA_PROCESS_OUTBOUND
REDIS_DB_INDEX
REDIS_HOST
REDIS_NUMBER_PORT
REGISTRY_URL
TEMPLATE_SERVICE_BASE_URL
```

</details>

**Problems:**

`keyspace-name` variable is not being used. Although `spring.data.cassandra.keyspace-name` which has been commented out was being used.

**Misnamed:**

`CDN_MINI_LOGIN_ID` -> `CDN_MINIO_LOGIN_ID`
`REDIS_PORT` -> `REDIS_NUMBER_PORT`

**Missing:**

`KAFKA_GENERIC_TRANSFORMER_TOPIC`

**Comment by pankajjangid05** [comment]
These env. variables are use by diksha, so we can set empty value in these env. variable. 

SUNBIRD_CLOUD_MEDIA_STORAGE_CONTAINER
SUNBIRD_CLOUD_MEDIA_STORAGE_KEY
SUNBIRD_CLOUD_MEDIA_STORAGE_SECRET
SUNBIRD_CLOUD_MEDIA_STORAGE_TYPE
SUNBIRD_CLOUD_MEDIA_STORAGE_URL

**Comment by chinmoy12c** [comment]
Default values in the `application.properties` need to be cleaned up as well.

cc @pankajjangid05

**Comment by chinmoy12c** [comment]
<details>
<summary>Here is the filtered list of env variables for inbound. </summary>
<br>

```
AZURE_BLOB_STORE_ACCOUNT_KEY
AZURE_BLOB_STORE_ACCOUNT_NAME
AZURE_BLOB_STORE_CONTAINER
BOOTSTRAP_SERVERS
CAFFEINE_CACHE_EXPIRE_DURATION
CAFFEINE_CACHE_MAX_SIZE
CAMPAIGN_ADMIN_TOKEN
CAMPAIGN_URL
CASSANDRA_KEYSPACE
CASSANDRA_PORT
CASSANDRA_URL
CDAC_BASE_URL
CDN_MINIO_APP_ID
CDN_MINIO_BUCKET_ID
CDN_MINIO_FA_KEY
CDN_MINIO_FA_URL
CDN_MINIO_LOGIN_ID
CDN_MINIO_PASS
CDN_MINIO_URL
ENV
FORMS_DB_HOST
FORMS_DB_NAME
FORMS_DB_PASSWORD
FORMS_DB_PORT
FORMS_DB_USERNAME
FUSIONAUTH_KEY
FUSIONAUTH_URL
KAFKA_CAMPAIGN_TOPIC
KAFKA_INBOUND_ERROR_TOPIC
KAFKA_INBOUND_GS_OPTED_OUT_TOPIC
KAFKA_INBOUND_PROCESSED_TOPIC
KAFKA_MESSAGE_REPORT_TOPIC
KAFKA_OUTBOUND_TOPIC
MAX_SIZE_FOR_AUDIO
MAX_SIZE_FOR_DOCUMENT
MAX_SIZE_FOR_IMAGE
MAX_SIZE_FOR_VIDEO
REDIS_DB_INDEX
REDIS_HOST
REDIS_PORT
REGISTRY_URL
SELECTED_FILE_CDN
SUNBIRD_CLOUD_MEDIA_STORAGE_CONTAINER
SUNBIRD_CLOUD_MEDIA_STORAGE_KEY
SUNBIRD_CLOUD_MEDIA_STORAGE_SECRET
SUNBIRD_CLOUD_MEDIA_STORAGE_TYPE
SUNBIRD_CLOUD_MEDIA_STORAGE_URL
```

</details>



**Missing Keys:**



`AZURE_BLOB_STORE_ACCOUNT_KEY`
`AUTH_USER_INFO`
`AZURE_BLOB_STORE_ACCOUNT_NAME`
`AZURE_BLOB_STORE_CONTAINER`
`MAX_SIZE_FOR_AUDIO`
`MAX_SIZE_FOR_DOCUMENT`
`MAX_SIZE_FOR_IMAGE`
`MAX_SIZE_FOR_VIDEO`
`SUNBIRD_CLOUD_MEDIA_STORAGE_CONTAINER`
`SUNBIRD_CLOUD_MEDIA_STORAGE_KEY`
`SUNBIRD_CLOUD_MEDIA_STORAGE_SECRET`
`SUNBIRD_CLOUD_MEDIA_STORAGE_TYPE`
`SUNBIRD_CLOUD_MEDIA_STORAGE_URL`

**Comment by chinmoy12c** [comment]
Outbound does not require any environment variables.

**Comment by chinmoy12c** [comment]
<details>
<summary>Here is the filtered list of env variables for broadcast-transformer. </summary>
<br>

```
BOOTSTRAP_SERVERS
CAFFEINE_CACHE_EXPIRE_DURATION
CAFFEINE_CACHE_MAX_SIZE
FORMS_DB_HOST
FORMS_DB_NAME
FORMS_DB_PASSWORD
FORMS_DB_PORT
FORMS_DB_USERNAME
KAFKA_BROADCAST_TRANSFORMER_TOPIC
KAFKA_PROCESS_OUTBOUND
REDIS_DB_INDEX
REDIS_HOST
REDIS_NUMBER_PORT
REGISTRY_URL
```

</details>



**Misnamed**
REDIS_PORT -> REDIS_NUMBER_PORT

**Comment by karntrehan** [comment]
@tushar5526 to discuss with @RyanWalker277

**Comment by geeky-abhishek** [comment]
one PR is created for a module. For details ask : @RyanWalker277 @tushar5526

**Comment by chinmoy12c** [comment]
@pankajjangid05 @chinmoy12c to share update about redundant redis containers.

**Comment by pankajjangid05** [comment]
One redis service removed from docker-compose which is not using anywhere. Currently we are using 2 cache services : 

1. **uci-api-scheduler-db** : using backend services
2. **cache** : using transport-socket

**Comment by RyanWalker277** [comment]
Updated #45 accordingly. @pankajjangid05 @chinmoy12c @tushar5526 please review.

**Comment by tushar5526** [comment]
@chinmoy12c please add in the remaining services as well.

**Comment by susheelvar** [comment]
@tushar5526 to pick this up.

**Comment by tushar5526** [comment]
@chinmoy12c can you list the environment variables required in uci-api service as well.

**Comment by chinmoy12c** [comment]
Here are the env variables being used in UCI-APIs:

```
# ADMIN TOKEN

ADMIN_TOKEN

# Postgres

PSQL_DB_URL
PSQL_DB_URL_DEV
POSTGRES_PASSWORD
POSTGRES_USER
POSTGRES_DB
DATABASE_DEBUG

# Redis

REDIS_HOST
REDIS_PORT
REDIS_PASS

# Kafka

KAFKA_HOST_DEV
KAFKA_USER
KAFKA_PASS
KAFKA_HOST
KAFKA_PORT
KAFKA_LOG_LEVEL

# FusionAuth

FUSIONAUTH_URL
# FUSIONAUTH_URL
FUSIONAUTH_KEY
FUSIONAUTH_ANONYMOUS_BOT_APP_ID
AUTH_PUBLIC_KEY

# Hasura

HASURA_GRAPHQL_DATABASE_URL
HASURA_GRAPHQL_ENABLE_CONSOLE
HASURA_GRAPHQL_ENABLED_LOG_TYPES
HASURA_GRAPHQL_ADMIN_SECRET

# Other Services

UCI_CORE_BASE_URL
TRANSFORMER_BASE_URL
GRAPHQL_BASE_URL

ENV=dev
VAULT_TOKEN
VAULT_ADDR

# Telemetry - Login using your Github Account

POSTHOG_API_KEY
POSTHOG_BASE_URL
POSTHOG_BATCH_SIZE

POSTHOG_FLUSH_INTERVAL


INSTANCE_ID

# ODK

ODK_BASE_URL
ODK_USERNAME
ODK_PASSWORD

# Encryption

ENCRYPTION_KEY
ENV

# Minio
MINIO_MEDIA_UPLOAD_URL
MINIO_GET_SIGNED_FILE_URL
```

**Comment by karntrehan** [comment]
@RyanWalker277 I think this is already done? Please link the ticket, PR here and close this ticket.

**Comment by RyanWalker277** [comment]
Completed in https://github.com/samagra-comms/docker-deploy/commit/2ef571c85ff3d43588d715b27862f6083b4f6335
