### ISSUE TITLE
Remove Installv2.sh and replace it with install_manual.sh

### ISSUE THREAD

**Issue by RyanWalker277** [samagra-comms/docker-deploy#65]
The purpose is to unify all the scripts into a single one which can help deploy UCI through a single run

**Comment by tushar5526** [comment]
Please modify installv2.sh only. Manual installation script was supposed to be a temporary task.

**Comment by tushar5526** [comment]
Please test the final script as well, let me know if you need any test servers if gitpod does not works.

**Comment by chinmoy12c** [comment]
@RyanWalker277 is this done or there are still some changes that are required?

**Comment by karntrehan** [comment]
PR raised. Readme updated as well.
