### ISSUE TITLE
Identify better ways of handling logs from UCI system

### ISSUE THREAD

**Issue by karntrehan** [samagra-comms/docker-deploy#67]

**Comment by karntrehan** [comment]
Staging worked well. @tushar5526 to deploy on prod.

**Comment by tushar5526** [comment]
![image](https://github.com/samagra-comms/docker-deploy/assets/30565750/a750b1b9-a7e9-4651-afde-3be0ff38df60)
![image](https://github.com/samagra-comms/docker-deploy/assets/30565750/76bb57b8-20e4-4699-8adc-7ae32a7b98c4)

Deployed the new configurations to staging, prod docker swarm and prod db server.

**Comment by tushar5526** [comment]
![image](https://github.com/samagra-comms/docker-deploy/assets/30565750/a750b1b9-a7e9-4651-afde-3be0ff38df60)
![image](https://github.com/samagra-comms/docker-deploy/assets/30565750/76bb57b8-20e4-4699-8adc-7ae32a7b98c4)

Deployed the new configurations to staging, prod docker swarm and prod db server. Devs to test it now.
