### ISSUE TITLE
Setup seed data - Merge dev with main and create a release

### ISSUE THREAD

**Issue by tushar5526** [samagra-comms/docker-deploy#70]
- [x] Test the `manual-setup.sh` and setup DBs 
- [ ] When the project is up and running successfully, copy the seed data to dev branch
- [ ] Merge dev to main and create a release

**Comment by chinmoy12c** [comment]
@tushar5526 can you share some context on this issue and what's the current state?

**Comment by tushar5526** [comment]
Setup the project using the new updated scripts. 
Seed all the databases with demo bot IDs to setup seed data. 
Update the deployment script to seed the above seed data for new users, so they can get an e2e setup with them. 

Seed data will not require writing a setup script with APIs call to bootstrap UCI. It's an easier way to setup the project, but kind of blackbox for users on what was done. 

No progress on this as this was de-priortized. @RyanWalker277 already has other BE issues to work on.

**Comment by karntrehan** [comment]
Server setup done. To test on the same server.

**Comment by geeky-abhishek** [comment]
Can be verified only when UCI setup is done on the 143. server (Playground server setup is in progress)

**Comment by geeky-abhishek** [comment]
@chinmoy12c and @RyanWalker277 to connect today for this

**Comment by karntrehan** [comment]
Discussion had. @geeky-abhishek to work on the hardcoded web channel build.

**Comment by karntrehan** [comment]
Posthog and other external depencies to be made optional (currently) and removed. @RyanWalker277 to work with @chinmoy12c on this.

**Comment by karntrehan** [comment]
Environment variables to be cleanup up as well. Tracked here: #33

**Comment by karntrehan** [comment]
Need to add a delay in data insertion. This is to allow the container to spin up and setup completely.

**Comment by RyanWalker277** [comment]
Here is a list of tasks which are needed to be completed before merging the PR related to this ticket.

- [ ] Automate Hassura Queries
- [ ] Add database migration step to uci-apis dockerfile
- [ ] Review kafka stack changes
- [ ] Add documentation for generating essential secrets
- [ ] Aggregate error while uploading form

Here is a list of those tickets which are important for v2 setup but not a blocker in merging the PR

- [ ] #33

**Comment by geeky-abhishek** [comment]
.env cleaup is still pending. @RyanWalker277   Will create a separate ticket for this

**Comment by geeky-abhishek** [comment]
@chinmoy12c  & @RyanWalker277 will test this
