### ISSUE TITLE
Reduce JVM memory usage

### ISSUE THREAD

**Issue by chinmoy12c** [samagra-comms/docker-deploy#71]
Currently, the transaction layer services take up a lot of RAM. we need to reduce the RAM consumption of all our services. Here is the doc elaborating on the analysis of the RAM and method to reduce the consumption.

https://docs.google.com/document/d/1QceK1fbkc_dRIJe1GPT13RvbdE0A_XRGizhVKmKHWmo/edit?usp=sharing

**Comment by karntrehan** [comment]
Plan of action: 
@chinmoy12c and @tushar5526 

* Deploy RAM limit to staging. Do not change JVM.
* Test for segment 2 which has 1L test users. 
* Change GC if required
* Once testing completed move to prod deployment

**Comment by geeky-abhishek** [comment]
@chinmoy12c to update whether to pick this today or not.

**Comment by geeky-abhishek** [comment]
Deployed to production on friday by @pankajjangid05
