### ISSUE TITLE
Fix conversation flow in the setup by install.py

### ISSUE THREAD

**Issue by RyanWalker277** [samagra-comms/docker-deploy#87]
Currently, the infrastructure set up by `install.py` does not support bot conversation. The errors need to be debugged to make the bot conversation flow work.

**Comment by RyanWalker277** [comment]
Update: Bot conversation is working on the `playground` server. The script needs to be updated to incorporate the changes and minor cleanup of the script.

**Comment by geeky-abhishek** [comment]
@RyanWalker277 working on code cleanup and expected to close by tomorrow EOD.

**Comment by karntrehan** [comment]
Internal demo = Thursday
Leadership demo = Friday

**Comment by geeky-abhishek** [comment]
Leadership demo = Next Week
