### ISSUE TITLE
Make .env adapter friendly

### ISSUE THREAD

**Issue by RyanWalker277** [samagra-comms/docker-deploy#89]

**Comment by karntrehan** [comment]
To take staging env and clean that up.

**Comment by aakashyadav-kgp** [comment]
Admin panel IPs pending. Rest is done.

**Comment by aakashyadav-kgp** [comment]
env work is done, debugging on UCI APIs

**Comment by aakashyadav-kgp** [comment]
Web channel needs to be debugged. Env variables need to be added.
