### ISSUE TITLE
Fix UCI-Setup Blockers

### ISSUE THREAD

**Issue by RyanWalker277** [samagra-comms/docker-deploy#90]
Currently, UCI can be setup with a single script run. But there are some blockers that either increase manual steps or pose a problem in the smooth functioning of UCI. Here is a list of the blockers:

- [x] Bot Image migration isn't applied by UCI-APIs which requires adopters to manually sync the database with the schema (The corrected build can be found [here](https://hub.docker.com/layers/samagragovernance/uci-apis/demo-UCI/images/sha256-0f8472134b97679a35ab471086343d13b48a478224f6423cf45e96ea7a44e9f7?context=repo) )
- [x] Environment variables get hardcoded in the image build for Web-Channel (https://github.com/samagra-comms/uci-web-channel/pull/152)

**Comment by chinmoy12c** [comment]
PR raised to be reviewed by @geeky-abhishek .
